Repository KUSITMS-Team-A/Frontend-web, pull requests merged in 2023-11, with the labels that each got.

#6 [#2] feat: 가게 찾기 페이지 디자인 완료
  .env.example
  README.md
  assets/svg/Beauty.svg
  assets/svg/Cafe.svg
  assets/svg/Culture.svg
  assets/svg/DownArrow.svg
  assets/svg/Edit.svg
  assets/svg/EmptyHeart.svg
  assets/svg/Etc.svg
  assets/svg/Food.svg
  assets/svg/FullHeart.svg
  assets/svg/Search.svg
  assets/svg/UpArrow.svg
  assets/svg/unselect/uBeauty.svg
  assets/svg/unselect/uCafe.svg
  assets/svg/unselect/uCulture.svg
  assets/svg/unselect/uEtc.svg
  assets/svg/unselect/uFood.svg
  components/Map.tsx
  components/Marker/Icon/IconMarker.tsx
  components/Marker/Name/Name.styles.ts
  components/Marker/Name/NameMarker.tsx
  components/SearchInput.tsx
  components/StoreInfo.tsx
  components/Storelist.tsx
  components/organisms/Filter.tsx
  components/organisms/Header.tsx
  components/styles/Search.styles.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/search/index.tsx
  states/Store.ts
  styles/colors.tsx
  utils/TypeImg.tsx
Labels: feat

#40 [#39] fix : 서브메뉴 디자인 변경 및 링크추가
  components/atoms/basics.ts
  components/hooks/useCouponData.ts
  components/hooks/usePopupData.ts
  components/hooks/useUniv.ts
  components/organisms/Header.tsx
  components/styles/PopUp.styles.tsx
  components/styles/coupon/style.ts
  components/styles/popup/style.ts
  components/styles/user/second/style.ts
  pages/api/StoreAPI.ts
  pages/api/axiosInstance.ts
  pages/api/coupon.ts
  pages/api/login.ts
  pages/api/others.ts
  pages/student/coupon/index.tsx
  pages/student/coupon/register/Inputs.tsx
  pages/student/popup/index.tsx
  pages/user/form/index.tsx
Labels: 🐛 fix

#46 [#45] feat : 개별 대시보드 개발 및 전체대시보드 색상 수정
  components/StoreInfo.tsx
  components/atoms/ChartBackground.svg
  components/atoms/modalState.tsx
  components/hooks/useModal.ts
  components/hooks/usePopupData.ts
  components/organisms/Header.tsx
  components/organisms/Modal.tsx
  components/styles/CInputs.style.ts
  components/styles/Inputs.style.ts
  components/styles/SecondBox.styles.ts
  components/styles/dashboardDetail/style.ts
  package-lock.json
  package.json
  pages/api/ContractAPI.ts
  pages/api/login.ts
  pages/apply/form/index.tsx
  pages/apply/index.tsx
  pages/dashboard/BackgroundedChart.tsx
  pages/dashboard/BarChart.tsx
  pages/dashboard/ComposedChart.tsx
  pages/dashboard/FifthBox.tsx
  pages/dashboard/FirstChart.tsx
  pages/dashboard/FourthBox.tsx
  pages/dashboard/ListChart.tsx
  pages/dashboard/OneStackChart.tsx
  pages/dashboard/PieCharts.tsx
  pages/dashboard/StackCharts.tsx
  pages/dashboard/[store].tsx
  pages/dashboard/index.tsx
  pages/student/coupon/register/Inputs.tsx
  pages/student/popup/index.tsx
  pages/student/popup/register/Inputs.tsx
  pages/user/auth/index.tsx
  pages/user/form/index.tsx
  pages/user/index.tsx
Labels: ✨ feat, 💄 style

#48 [#47] style : 전체 대시보드 가게 메뉴바 추가
  components/hooks/usePopupData.ts
  pages/dashboard/[store].tsx
  pages/dashboard/index.tsx
  pages/student/popup/index.tsx
  pages/user/form/index.tsx
  pages/user/index.tsx
Labels: 💄 style

#54 [#51] feat/style: 제휴 가게 페이지 남은 api 연동 및 스타일 수정
  @types/Contract.d.ts
  components/hooks/usePopupData.ts
  components/styles/Contact.styles.tsx
  next.config.js
  package-lock.json
  package.json
  pages/_document.tsx
  pages/contact/index.tsx
  pages/contact/store/[id].tsx
  pages/user/index.tsx
  setupProxy.js
Labels: ✨ feat, 💄 style, 🐛 fix

#55 [#34] style: 가게 상세 정보 영업시간 디자인 반영
  assets/svg/SmallDropDown.svg
  assets/svg/SmallDropTop.svg
  components/StoreInfo.tsx
Labels: ✨ feat, 💄 style

#56 [#49] fix : 로그인 오류 수정 및 로그아웃 모달추가
  components/hooks/useCouponData.ts
  components/hooks/useStores.ts
  components/organisms/Header.tsx
  components/organisms/Modal.tsx
  pages/api/coupon.ts
  pages/api/login.ts
  pages/api/others.ts
  pages/dashboard/index.tsx
  pages/student/coupon/index.tsx
  pages/student/coupon/register/Inputs.tsx
  pages/student/popup/index.tsx
  pages/user/index.tsx
Labels: ✨ feat, 🐛 fix

#58 [#52] feat: 제휴가게 등록 페이지 완성 후 API 연결
  components/organisms/Modal/ SearchModal.tsx
  components/styles/SearchModal.styles.ts
  pages/api/ContractAPI.ts
  pages/contact/enroll/index.tsx
  pages/contact/index.tsx
  states/Enroll.ts
Labels: ✨ feat

#62 [#57] feat: 쿠폰 미리보기 추가
  components/atoms/CouponBackground.svg
  pages/student/coupon/index.tsx
  pages/student/coupon/register/Inputs.tsx
  pages/student/coupon/register/index.tsx
  pages/student/popup/register/Inputs.tsx
Labels: ✨ feat

#68 [#63] feat: 대시보드 데이터 다양하게
  assets/svg/background2.png
  components/organisms/Header.tsx
  components/styles/dashboard/style.ts
  pages/dashboard/FirstLayerChart.tsx
  pages/dashboard/ListChart.tsx
  pages/dashboard/PieCharts.tsx
  pages/dashboard/StackCharts.tsx
  pages/dashboard/index.tsx
  pages/index.tsx
Labels: ✨ feat, 💄 style

#66 [#64] feat: 정산관리 페이지
  assets/svg/One.svg
  assets/svg/Three.svg
  assets/svg/Two.svg
  components/organisms/Modal/OperateModal.tsx
  components/organisms/Modal/StampModal.tsx
  components/styles/Contact.styles.tsx
  components/styles/Search.styles.tsx
  components/styles/SecondBox.styles.ts
  components/styles/dashboard/style.ts
  pages/contact/index.tsx
  pages/dashboard/index.tsx
  pages/search/index.tsx
  pages/student/coupon/index.tsx
  public/favicon.ico
  public/manifest.json
Labels: ✨ feat

#71 [feat#69] : 제휴가게 - 가게상세 - 대시보드 연결
  pages/contact/store/[id].tsx
Labels: ✨ feat

#79 [#78] chore: console.log 삭제
  components/hooks/usePopupData.ts
  components/hooks/useStores.ts
  components/organisms/Header.tsx
  components/organisms/Modal/ SearchModal.tsx
  pages/api/StoreAPI.ts
  pages/api/axiosInstance.ts
  pages/api/login.ts
  pages/contact/index.tsx
  pages/contact/store/[id].tsx
  pages/search/index.tsx
  pages/student/coupon/register/Inputs.tsx
  pages/student/coupon/register/index.tsx
  pages/student/popup/index.tsx
  pages/student/popup/register/Inputs.tsx
  pages/user/auth/index.tsx
  pages/user/form/index.tsx
Labels: ✏️ chore

#80 Release 2.0.1
  components/hooks/usePopupData.ts
  components/hooks/useStores.ts
  components/organisms/Header.tsx
  components/organisms/Modal/ SearchModal.tsx
  pages/api/StoreAPI.ts
  pages/api/axiosInstance.ts
  pages/api/login.ts
  pages/contact/index.tsx
  pages/contact/store/[id].tsx
  pages/search/index.tsx
  pages/student/coupon/register/Inputs.tsx
  pages/student/coupon/register/index.tsx
  pages/student/popup/index.tsx
  pages/student/popup/register/Inputs.tsx
  pages/user/auth/index.tsx
  pages/user/form/index.tsx
Labels: Release
